default:  fxctmp9_tmp\SDK_lightmappedgeneric_flashlight_vs30.inc shaders\fxc\SDK_lightmappedgeneric_flashlight_vs30.vcs fxctmp9_tmp\SDK_lightmappedgeneric_flashlight_ps30.inc shaders\fxc\SDK_lightmappedgeneric_flashlight_ps30.vcs fxctmp9_tmp\SDK_lightmappedgeneric_ps30.inc shaders\fxc\SDK_lightmappedgeneric_ps30.vcs fxctmp9_tmp\SDK_lightmappedgeneric_vs30.inc shaders\fxc\SDK_lightmappedgeneric_vs30.vcs

fxctmp9_tmp\SDK_lightmappedgeneric_flashlight_vs30.inc shaders\fxc\SDK_lightmappedgeneric_flashlight_vs30.vcs: SDK_lightmappedgeneric_flashlight_vs20.fxc common_pragmas.h common_hlsl_cpp_consts.h common_vs_fxc.h common_fxc.h
	perl D:\SOURCEREPOZ\BCWSbase\sp\src\devtools\bin\fxc_prep.pl   -source "D:\SOURCEREPOZ\BCWSbase\sp\src" SDK_lightmappedgeneric_flashlight_vs20.fxc-----SDK_lightmappedgeneric_flashlight_vs30
	echo SDK_lightmappedgeneric_flashlight_vs20.fxc>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_vs_fxc.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt

fxctmp9_tmp\SDK_lightmappedgeneric_flashlight_ps30.inc shaders\fxc\SDK_lightmappedgeneric_flashlight_ps30.vcs: SDK_lightmappedgeneric_flashlight_ps2x.fxc common_vertexlitgeneric_dx9.h common_hlsl_cpp_consts.h common_lightmappedgeneric_fxc.h common_pragmas.h shader_constant_register_map.h common_fxc.h common_flashlight_fxc.h common_ps_fxc.h
	perl D:\SOURCEREPOZ\BCWSbase\sp\src\devtools\bin\fxc_prep.pl   -source "D:\SOURCEREPOZ\BCWSbase\sp\src" SDK_lightmappedgeneric_flashlight_ps2x.fxc-----SDK_lightmappedgeneric_flashlight_ps30
	echo SDK_lightmappedgeneric_flashlight_ps2x.fxc>> filestocopy.txt
	echo common_vertexlitgeneric_dx9.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_lightmappedgeneric_fxc.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo shader_constant_register_map.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_flashlight_fxc.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt

fxctmp9_tmp\SDK_lightmappedgeneric_ps30.inc shaders\fxc\SDK_lightmappedgeneric_ps30.vcs: SDK_lightmappedgeneric_ps20b.fxc common_hlsl_cpp_consts.h lightmappedgeneric_ps2_3_x.h common_pragmas.h common_lightmappedgeneric_fxc.h common_ps_fxc.h common_flashlight_fxc.h common_fxc.h
	perl D:\SOURCEREPOZ\BCWSbase\sp\src\devtools\bin\fxc_prep.pl   -source "D:\SOURCEREPOZ\BCWSbase\sp\src" SDK_lightmappedgeneric_ps20b.fxc-----SDK_lightmappedgeneric_ps30
	echo SDK_lightmappedgeneric_ps20b.fxc>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo lightmappedgeneric_ps2_3_x.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_lightmappedgeneric_fxc.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt
	echo common_flashlight_fxc.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt

fxctmp9_tmp\SDK_lightmappedgeneric_vs30.inc shaders\fxc\SDK_lightmappedgeneric_vs30.vcs: SDK_lightmappedgeneric_vs20.fxc common_pragmas.h common_hlsl_cpp_consts.h common_vs_fxc.h common_fxc.h
	perl D:\SOURCEREPOZ\BCWSbase\sp\src\devtools\bin\fxc_prep.pl   -source "D:\SOURCEREPOZ\BCWSbase\sp\src" SDK_lightmappedgeneric_vs20.fxc-----SDK_lightmappedgeneric_vs30
	echo SDK_lightmappedgeneric_vs20.fxc>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_vs_fxc.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt

